services:
  cloud:
    image: cloud
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - database

  database:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cloudv1
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dockerUtilities/import.sql:/docker-entrypoint-initdb.d/import.sql
  
volumes:
  postgres_data: